name: Pull from Lokalise
run-name: Pull from Lokalise [${{ github.ref_name }}] ${{ github.event.after }}
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      LOKALISE_FILE_FORMAT: ${{ vars.LOKALISE_FILE_FORMAT }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Lokalise CLI
        run: |
          if [ ! -f ./bin/lokalise2 ]; then
            curl -sfL https://raw.githubusercontent.com/lokalise/lokalise-cli-2-go/master/install.sh | sh || {
              echo "Failed to install Lokalise CLI"
              exit 1
            }
          else
            echo "Lokalise CLI already installed, skipping installation."
          fi

      - name: Pull Localization Files from Lokalise
        env:
          LOKALISE_CLI_ADD_PARAMS: ${{ vars.LOKALISE_PULL_ADDITIONAL_PARAMS }}
          LOKALISE_PROJECT_ID: ${{ vars.LOKALISE_PROJECT_ID }}
          LOKALISE_API_TOKEN: ${{ secrets.LOKALISE_API_TOKEN }}
        run: |
          chmod +x .github/scripts/lokalise_download.sh
          
          echo "Running lokalise_download.sh script..."
          
          . ./.github/scripts/lokalise_download.sh
          
          download_files "$LOKALISE_PROJECT_ID"
                
          if [ $? -ne 0 ]; then
            echo "Error during file download"
            echo "has_changes=false" >> $GITHUB_ENV
            exit 1
          fi

          if [[ -z $(git status "$(find "${{ env.LOKALISE_FOLDER_PATH }}" -name "*.${{ env.LOKALISE_FILE_FORMAT }}")" --untracked-files=no --porcelain) ]]; then
            echo "No translation file changes detected after pulling from Lokalise"
            echo "has_changes=false" >> $GITHUB_ENV
          else
            echo "Translation file changes detected after pulling from Lokalise"
            echo "has_changes=true" >> $GITHUB_ENV
          fi

      - name: Commit and Push Changes
        if: env.has_changes == 'true'
        env:
          LOKALISE_BRANCH_MARKER: ${{ vars.LOKALISE_BRANCH_MARKER }}
          LOKALISE_FOLDER_PATH: ${{ vars.LOKALISE_TRANSLATIONS_PATH }}
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"

          SHORT_SHA=${GITHUB_SHA::6}  
          BRANCH_NAME="${{ env.LOKALISE_BRANCH_MARKER }}_${{ github.ref_name }}_$SHORT_SHA"
          echo "BRANCH_NAME is: $BRANCH_NAME"
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_ENV

          git checkout -b "$BRANCH_NAME" || git checkout "$BRANCH_NAME"
        
          git add "${{ env.LOKALISE_FOLDER_PATH }}/**/*.${{ env.LOKALISE_FILE_FORMAT }}" --force
          git commit -m 'Translations update'
          git push origin "$BRANCH_NAME"

      - name: Create Pull Request
        if: env.has_changes == 'true'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr create --base ${{ github.ref_name }} \
                       --head "${{ env.branch_name }}" \
                       --title "Lokalise translations update" \
                       --body "" || {
            echo "Failed to create a Pull Request"
            exit 1
          }

          echo "Pull Request created successfully."